spring:
  application:
    name: mybatis-plus-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis-plus-demo?characterEncoding=utf8&useSSL=false
    username: root
    password: weizibin123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: DatebookHikariCP

mybatis-plus:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      db-type: mysql
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: ''
